---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" or
      ansible_os_family == "Debian"

- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml

- name: Remove any conflicting packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ sssd_conflict_pkgs }}"
  tags:
    - sssd_pkg

- name: Stop and disable conflicting services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: yes
  with_items: "{{ sssd_conflict_services }}"
  tags:
    - sssd_service

- name: Install sssd package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sssd_pkgs }}"
  notify:
    - Restart sssd
  tags:
    - sssd_pkg

- name: Configure sssd service
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    owner: root
    group: root
  notify:
    - Restart sssd
  tags:
    - sssd_config

- name: Make sure sssd service is running
  service:
    name: "{{ sssd_service }}"
    state: started
  register: sssd_service_started
  tags:
    - sssd_config
    - sssd_pkg

- name: Make sure sssd service is enabled
  service:
    name: "{{ sssd_service }}"
    enabled: yes
  tags:
    - sssd_config

- block:
  - name: Ensure authconfig is installed
    package:
      name: authconfig
      state: installed

  - name: Check authconfig values
    command: authconfig --test
    changed_when: false
    register: sssd_authconfig_out

  - name: Enable sssd via authconfig
    command: authconfig --update --enablesssd --enablesssdauth
    when: sssd_authconfig_out.stdout.find('nss_sss is disabled') != -1 or sssd_authconfig_out.stdout.find('pam_sss is disabled') != -1 or sssd_authconfig_out.stdout.find('pam_ldap is enabled') != -1 or sssd_authconfig_out.stdout.find('nss_ldap is enabled') != -1

  - name: Disable nslcd via authconfig if configured
    command: authconfig --update --disableldap --disableldapauth
    when: sssd_authconfig_nslcd_disable and (sssd_authconfig_out.stdout.find('pam_ldap is enabled') != -1 or sssd_authconfig_out.stdout.find('nss_ldap is enabled') != -1)
  
  when: ansible_os_family == "RedHat" and sssd_authconfig_config
  tags:
    - sssd_config