---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat"

- name: Remove any conflicting packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ sssd_conflict_pkgs }}"

- name: Stop and disable conflicting services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: yes
  with_items: "{{ sssd_conflict_services }}"

- name: Install sssd package for RedHat
  yum:
    name: "{{ sssd_pkg }}"
    state: present
  notify:
    - Restart sssd
  tags:
    - sssd_pkg

- name: Configure sssd service
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    owner: root
    group: root
  notify:
    - Restart sssd
  tags:
    - sssd_config

- name: Make sure sssd service is running
  service:
    name: sssd
    state: started
  register: sssd_service_started
  tags:
    - sssd_config
    - sssd_pkg

- name: Make sure sssd service is enabled
  service:
    name: sssd
    enabled: yes
  tags:
    - sssd_config

- block:
  - name: Ensure authconfig is installed
    yum:
      name: authconfig
      state: installed

  - name: Check authconfig values
    command: authconfig --test
    changed_when: false
    register: sssd_authconfig_out

  - name: Enable sssd via authconfig
    command: authconfig --update --enablesssd --enablesssdauth
    when: sssd_authconfig_out.stdout.find('nss_sss is disabled') != -1 or sssd_authconfig_out.stdout.find('pam_sss is disabled') != -1 or sssd_authconfig_out.stdout.find('pam_ldap is enabled') != -1 or sssd_authconfig_out.stdout.find('nss_ldap is enabled') != -1

  - name: Disable nslcd via authconfig if configured
    command: authconfig --update --disableldap --disableldapauth
    when: sssd_authconfig_nslcd_disable and (sssd_authconfig_out.stdout.find('pam_ldap is enabled') != -1 or sssd_authconfig_out.stdout.find('nss_ldap is enabled') != -1)

  when: sssd_authconfig_config